sudo: required
language: node_js
node_js:
  - "0.12"
install:
  - "npm install -g typescript@>=1.5.0"
  - "npm install -g bower"
script:
    - ./updateAll.sh
    - cd example && karma start ../test/karma.conf.js
    - cd .. && cat coverage/*/lcov.info | example/node_modules/coveralls/bin/coveralls.js
notifications:
  slack: webcs:AnvBbkHIi7v9aTiS2H4suMkr
